export const STORAGE_KEYS = {
  dogs: "thedogmall.dogs",
  breedings: "thedogmall.breedings",
  pregnancies: "thedogmall.pregnancies",
  litters: "thedogmall.litters",
  puppies: "thedogmall.puppies",
  clients: "thedogmall.clients",
  expenses: "thedogmall.expenses",
  incomes: "thedogmall.incomes",
  tasks: "thedogmall.tasks",
  healthRecords: "thedogmall.healthRecords",
  heatCycles: "thedogmall.heatCycles",
  sales: "thedogmall.sales",
  waitlist: "thedogmall.waitlist",
  clientInteractions: "thedogmall.clientInteractions",
  kennelSettings: "thedogmall.kennelSettings",
  dogPhotos: "thedogmall.dogPhotos",
  dogDocuments: "thedogmall.dogDocuments",
  litterPhotos: "thedogmall.litterPhotos",
  lastBackupAt: "thedogmall.lastBackupAt",
} as const;
